apiVersion: v1
kind: Secret
metadata:
  name: community-db-secret
  namespace: leddit
type: Opaque
stringData:
  APP_NAME: community-service
  POSTGRES_USER: community
  POSTGRES_PASSWORD: community
  POSTGRES_DB: community
  DATABASE_URL: postgresql://community:community@community-db:5432/community
  RABBITMQ_URL: amqp://guest:guest@rabbitmq.leddit.svc.cluster.local:5672/
