apiVersion: v1
kind: Secret
metadata:
  name: post-db-secret
  namespace: leddit
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: posts_db
  DATABASE_URL: postgresql://postgres:postgres@post-db:5432/posts_db
