apiVersion: v1
kind: Secret
metadata:
  name: vote-db-secret
  namespace: leddit
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

  DATABASE_WRITE_URL: postgresql://postgres:postgres@vote-db:5432/voting_write_db
  DATABASE_READ_URL: postgresql://postgres:postgres@vote-db:5432/voting_read_db

  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
