services:
  #this post-db below should probably not be here since it should be able to be scaled independently??? idk man
  post-db:
    image: postgres:15
    container_name: post-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - leddit-network
    volumes:
      - post_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d posts_db"]

  post-service:
    build: .
    labels:
      logging_job: "leddit"
    container_name: post-service
    depends_on:
      post-db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - leddit-network
    volumes:
      - .:/app

volumes:
  post_db_data:

networks:
  leddit-network:
    external: true
