[project]
name = "post-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.136.1",
    "leddit-logging",
    "pika>=1.4.0",
    "psycopg2>=2.9.12",
    "pydantic>=2.13.3",
    "pydantic-settings>=2.14.0",
    "sqlalchemy>=2.0.49",
    "uvicorn>=0.46.0",
]
[project.optional-dependencies]
test = [
    "pytest>=7.0",
    "testcontainers>=4.0",
    "httpx>=0.27",
]

[tool.uv.sources]
leddit-logging = { git = "https://github.com/leddit-labs/leddit-platform.git", subdirectory = "leddit-logging", rev = "v0.1.0" }
