apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: leddit
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          envFrom:
            - secretRef:
                name: rabbitmq-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            exec:
              command: [rabbitmq-diagnostics, -q, ping]
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            exec:
              command: [rabbitmq-diagnostics, -q, ping]
            initialDelaySeconds: 30
            periodSeconds: 15
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rabbitmq-data
