
services:

  vote-db:
    image: postgres:16
    container_name: vote-db
    env_file: .env
    ports:
      - "5435:5432"
    volumes:
      - vote_data:/var/lib/postgresql/data
      - ./app/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    mem_limit: 300m
    networks:
      - leddit-network
  
  vote-write-api:
    build: .
    labels:
      logging_job: "leddit"
    container_name: vote-write-api
    command: uv run uvicorn app.commands.main:app --host 0.0.0.0 --port 8004 --reload
    depends_on:
      - vote-db
    env_file: .env
    ports:
      - "8004:8004"
    volumes:
      - ./app:/app/app
    mem_limit: 300m
    networks:
      - leddit-network

  vote-read-api:
    build: .
    labels:
      logging_job: "leddit"
    container_name: vote-read-api
    command: uv run uvicorn app.queries.main:app --host 0.0.0.0 --port 8005 --reload
    depends_on:
      - vote-db
    env_file: .env
    ports:
      - "8005:8005"
    volumes:
      - ./app:/app/app
    mem_limit: 300m
    networks:
      - leddit-network

  vote-projections:
    build: .
    labels:
      logging_job: "leddit"
    container_name: vote-projections
    command: uv run python -u -m app.consumer.main #-u because of debug print statements in container
    depends_on:
      - vote-db
    env_file: .env
    mem_limit: 200m
    networks:
      - leddit-network

volumes:
  vote_data:

networks:
  leddit-network:
    external: true
