apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
  namespace: leddit
  labels:
    app: apisix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      containers:
        - name: apisix
          image: apache/apisix:3.9.1-debian
          ports:
            - containerPort: 9080
              name: http
            - containerPort: 9443
              name: https
            - containerPort: 9180
              name: admin
          envFrom:
            - secretRef:
                name: apisix-secret
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /usr/local/apisix/conf/config.yaml
              subPath: config.yaml
            - name: config
              mountPath: /usr/local/apisix/conf/apisix.yaml
              subPath: apisix.yaml
      volumes:
        - name: config
          configMap:
            name: apisix-config
