apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: leddit
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v3.4.0
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.enable-remote-write-receiver
            - --storage.tsdb.retention.time=15d
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: data
              mountPath: /prometheus
      volumes:
        - name: config
          configMap:
            name: monitoring-config
        - name: data
          persistentVolumeClaim:
            claimName: prometheus-data
