apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: leddit
type: Opaque
stringData:
  KC_DB_PASSWORD: keycloak_password
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: keycloak_password
  GITHUB_CLIENT_ID: "Ov23liHFdnXlkmoagOaC"
  GITHUB_CLIENT_SECRET: "de9379548ef09cafaaae3d8fb2434130d58a9285"
