apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: leddit
type: Opaque
stringData:
  KC_DB_PASSWORD: keycloak_password
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: keycloak_password
  GITHUB_CLIENT_ID: "client_id_goes_here"
  GITHUB_CLIENT_SECRET: "client_secret_goes_here"
