services:
  community-service:
    container_name: community-service
    build: .
    labels:
      logging_job: "leddit" # For Alloy
      metrics_port: "8000"
    networks:
      - leddit-network
    ports:
      - "8002:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://community:community@db:5432/community
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: community-db
    environment:
      POSTGRES_USER: community
      POSTGRES_PASSWORD: community
      POSTGRES_DB: community
    ports:
      - "5433:5432"
    networks:
      - leddit-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U community"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:

networks:
  leddit-network:
    external: true
