apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: leddit
type: Opaque
stringData:
  POSTGRES_USER: leddit
  POSTGRES_PASSWORD: leddit
  POSTGRES_DB: leddit
  DATABASE_URL: postgresql+asyncpg://leddit:leddit@user-db:5432/leddit
