# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: community.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'community.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ommunity.proto\x12\tcommunity\".\n\x16\x43ommunityExistsRequest\x12\x14\n\x0c\x63ommunity_id\x18\x01 \x01(\t\"O\n\x17\x43ommunityExistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x12\n\nis_deleted\x18\x02 \x01(\x08\x12\x10\n\x08owner_id\x18\x03 \x01(\t\"?\n\x16MembershipCheckRequest\x12\x14\n\x0c\x63ommunity_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"T\n\x17MembershipCheckResponse\x12\x11\n\tis_member\x18\x01 \x01(\x08\x12\x14\n\x0cis_moderator\x18\x02 \x01(\x08\x12\x10\n\x08is_owner\x18\x03 \x01(\x08\x32\xc6\x01\n\x10\x43ommunityService\x12X\n\x0f\x43ommunityExists\x12!.community.CommunityExistsRequest\x1a\".community.CommunityExistsResponse\x12X\n\x0f\x43heckMembership\x12!.community.MembershipCheckRequest\x1a\".community.MembershipCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'community_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMUNITYEXISTSREQUEST']._serialized_start=30
  _globals['_COMMUNITYEXISTSREQUEST']._serialized_end=76
  _globals['_COMMUNITYEXISTSRESPONSE']._serialized_start=78
  _globals['_COMMUNITYEXISTSRESPONSE']._serialized_end=157
  _globals['_MEMBERSHIPCHECKREQUEST']._serialized_start=159
  _globals['_MEMBERSHIPCHECKREQUEST']._serialized_end=222
  _globals['_MEMBERSHIPCHECKRESPONSE']._serialized_start=224
  _globals['_MEMBERSHIPCHECKRESPONSE']._serialized_end=308
  _globals['_COMMUNITYSERVICE']._serialized_start=311
  _globals['_COMMUNITYSERVICE']._serialized_end=509
# @@protoc_insertion_point(module_scope)
